# Generated by Django 4.2.7 on 2023-12-04 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
